### ISSUE TITLE
 failed with error code 1 in None

### ISSUE THREAD

**Issue by aj1322001** [pegnet/pegnet-compose#10]
raspbian 64 bit - pi 4 

fresh install, error after running the sudo ./get_started.sh

Command "/usr/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-dbk8udt8 --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://www.piwheels.org/simple -- setuptools>=40.8.0 wheel "cffi>=1.1; python_implementation != 'PyPy'"" failed with error code 1 in None

**Comment by carrithers** [comment]
Hi @aj1322001 

This repo is no longer maintained. I have now updated the README to reflect that. Please take a look at the Prosper miner: https://github.com/FactomWyomingEntity/prosper-pool
