### ISSUE TITLE
Publish to docker hub

### ISSUE THREAD

**Issue by zzj0402** [pegnet/pegnet-compose#4]
Publish the image to docker hub so that it's easy to run.

**Comment by carrithers** [comment]
I agree that PegNet needs good support for Docker Hub. However, a PegNet image for Docker Hub needs to be managed by the PegNet repo, not by the PegNet Compose repo. I suggest you post an issue on that repo to ask them to add Docker Hub to the CI/CD. 

As far as PegNet Compose is concerned, the reason that everything in this repo is compiled from source is to cater to ARM architectures. The Factomd, Walletd and Factom-Cli repos on Docker Hub do not currently have images for ARM.
