### ISSUE TITLE
Errors Launching on Windows

### ISSUE THREAD

**Issue by joesixpack** [pegnet/pegnet-compose#8]
Docker...

![image](https://user-images.githubusercontent.com/23145642/66408568-0a67e480-e9a4-11e9-85a0-97b14dde751a.png)

**Comment by dwjorgeb** [comment]
@joesixpack can you please elaborate what steps did you take to arrive at this error?

**Comment by joesixpack** [comment]
I follow the README.md for pegnet-compose.  This was on Windows.  I don't think it likes the bootstrap file.

**Comment by joesixpack** [comment]
Updated the repository, rebuilt successfully and now a new error:

![image](https://user-images.githubusercontent.com/23145642/79683021-ee0ef500-81db-11ea-9a22-51967c0f00ca.png)

![image](https://user-images.githubusercontent.com/23145642/79683055-28789200-81dc-11ea-8aa4-a7f776327e9e.png)

**Comment by carrithers** [comment]
Hi @joesixpack 

Apologies for the slow response. This repo is no longer maintained and I will be closing this issue. If you're still around please take a look at the Prosper miner: https://github.com/FactomWyomingEntity/prosper-pool
